language: c++
sudo: enabled
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository universe
  - sudo apt-get update 
  - sudo apt-get install -y software-properties-common
  - sudo apt-get update
  - sudo apt-get install gcc-7 g++-7 gcc-7-multilib g++-7-multilib cmake3 -y
  - sudo apt-get install libboost-dev libboost-all-dev libmysqlclient-dev -y
  - sudo apt-get install libmysqlcppconn-dev -y

compiler:
  - g++
  
 
# Build steps
script:
  - g++ --version
  - mkdir build
  - cd build
  - cmake .. -DSAPPHIRE_BOOST_VER="1.54.0" -DCMAKE_CXX_COMPILER=g++-7 && make -j 3
  - cd ..
  - bash sql_import.sh
